import '@fortawesome/fontawesome-free/css/all.min.css';
import type { Metadata } from "next";
import "./globals.css";

import Navpar from "../_compnt/Navpar";
import Footer from "../_compnt/Footer";
import MyApp from "./_EXTINTIN/maseg";
import UserProvider from '../UserProvider';
import AppContextProvider from '../types/context'; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen justify-between w-full">
        <UserProvider>
<AppContextProvider>
            <Navpar />
            <main className="w-full min-h-screen">
              {children}
            </main>
            <Footer />
            <MyApp />
</AppContextProvider>
        </UserProvider>
      </body>
    </html>
  );
}
